---
title: "Ebola_cases"
author: "Jenny Yijian Huang"
date: '2022-05-10'
output: html_document
---
# Ebola incidence data.

# Reading in data
```{r}
path_data= "Ebola/Guinea_modified.csv"
```

```{r}
# Ebola Data
d <- readr::read_csv(
  path_data,
  col_types = readr::cols(
    .default            = readr::col_double(),
    Location            = readr::col_character(),
    `Ebola data source` = readr::col_character(),
    `Indicator type`    = readr::col_character(),
    `Case definition`   = readr::col_character()
  )
) %>%
  dplyr::select(-(2:4)) %>%
  dplyr::group_by(.data$Location) %>%
  dplyr::summarize_all(sum) %>%
  tibble::column_to_rownames("Location") %>%
  as.matrix

nam <- dimnames(d)
dimnames(d) <- NULL
#d[, 1 : 10]
T_k_ebola <- d[which(nam[[1]] == "GUECKEDOU"), ] # Ebola started in the GUECKEDOU prefecture

# # Observed data (incidence)
print(T_k_ebola)
print(nam[[1]][14])
print(nam[[2]][c(1:3, 71:73)])
barplot(T_k_ebola, xlab = "Week")

K     <- length(T_k_ebola) # number of time periods
t_end <- 7 * K
ts    <- seq(0, t_end, by = 7) # observation schedule
```

```{r}
# Observed data
S0 <- 291823 # https://en.wikipedia.org/wiki/Prefectures_of_Guinea
I0 <- 5
Y_ebola <- list(T_k = T_k_ebola, F_k = NULL, I0 = I0, S0 = S0, ts = ts, t_end = t_end)
```

# Plot of weekly incidence data over 73 weeks
```{r}
plot(x = Y_ebola$ts, y = c(0, Y_ebola$T_k), main="Ebola Incidence Observed", sub="each point one week", xlab="Time (days)", ylab="New Infections")
```

```{r}
length(Y_ebola$T_k) # 73 observations (weeks)
length(Y_ebola$ts) # 74 (time points)
```

```{r}
length(Y_ebola$T_k) # 73
length(seq(0,18.25, 0.25)) # Write the timescale in terms of months (instead of days). 74

Y_ebola$ts <- seq(0,18.25, 0.25)
Y_ebola$t_end <- 18.25
```

# 73 data points observed, 18.25 months. 12/2013 - 05/2015.
```{r}
Y_ebola 
```


```{r}
# The first 4 observations contain 0's and the last 21 observations, 5 months, are 0's. We cannot learn beta in a segment without any infection or recovery events. Hence, we only have enough data to reasonably be able to learn beta_i for months 2 - 12.
length(Y_ebola$T_k[5:52]) # 48
length(seq(0,12, 0.25)) # ts in terms of months (instead of days). 49.
```

```{r}
# run the following code chunk once.
Y_ebola$T_k <- Y_ebola$T_k[5:52]
Y_ebola$ts <- seq(0,12, 0.25)
Y_ebola$t_end <- 12

print(length(Y_ebola$T_k))
print(length(Y_ebola$ts))

Y_ebola
```

# Plot of weekly incidence data over 12 months. 01/2014 - 12/2014.
```{r}
plot(x = Y_ebola$ts, y = c(0, Y_ebola$T_k), main="Ebola Incidence Observed", sub="Infections observed on a weekly basis (Jan to Dec, 2014) ", xlab="Time (in months)", ylab="New Infections")
```


```{r}
theta0 <- list("R0" = 1, "beta" = 3e-7, "gamma" = 0.8, "shape"=1, "lambda"=1)
```

```{r}
ebola_6 <- run_DAMCMC_complete_smallh6(
  theta0, Y_ebola, N = 20000,
  rho = 0.2, param = "bg", approx = "ldp",
  iota_dist = "exponential", gener = FALSE, b = 1/2,
  thin = 1, plt = 6000,
  par_prior = list(
    a_beta = 0.1, b_beta = 0.1,
    a_gamma = 1, b_gamma = 1,
    a_R0 = 2, b_R0 = 2,
    a_lambda = 1, b_lambda = 1,
    a_pi11 = 1, b_pi11 = 100,
    a_pi01 = 500, b_pi01 = 500
  ), 
  length_delta = 11,
  x_b_ratio = 2,
  gamma=0.8
  )
```

```{r}
ebola_6$theta_rate_accept # theta = (dbeta, beta).
ebola_6$x_rate_accept # latent data.
```


```{r}
print(analyze_dbeta(ebola_6$dbeta_lst))
barplot(analyze_dbeta(ebola_6$dbeta_lst)[[2]], main="Delta Configurations", xlab="Change Point Location",  
 ylab="Proportion of MCMC Samples",names.arg = seq(1,11),
 border="blue")
# abline(h=1/2, col="blue", lty="dashed", lwd=4)
```
Plot results
```{r}
plot(x = Y_ebola$ts, y = c(0, Y_ebola$T_k), main="Ebola Incidence Observed", sub="Infections observed on a weekly basis (Jan. to Dec. 2014) ", xlab="Time (in months)", ylab="New Infections")
abline(v=c(2,8),lwd=2,col="red")
```
Analyze Top Configurations of Delta:

```{r}
dex <- changepoint_locations(ebola_6$dbeta_lst, 5000) 
# rename the columns
dex <- dex %>% 
  mutate('change1' = dex$'1', 'change2' = dex$'2', 'change3' = dex$'3', 'change4' = dex$'4')
```


```{r}
# create a column that unites change_point in each sample into one string.
dex <- dex %>% 
  unite("change_points", change1:change4, sep = ", ", remove=TRUE, na.rm=TRUE)
```

```{r fig.width=2, fig.height=2}
dex %>% 
  count("change_points") %>% 
  mutate(propr = freq/sum(freq)) %>% 
  arrange(desc(freq)) %>% 
  head(5) %>% 
  ggplot(data = ., aes(x = change_points, y = propr)) +
  geom_bar(stat = "identity") +
  labs(title = "Top Change Point Configurations", subtitle = "Ebola Epidemic (Jan-Dec. 2014)", y = "Proportion of MCMC Samples", x = "Change Point Times (Month)") + 
  theme_bw()
```


