---
title: "f_log_cp"
author: "Jenny Yijian Huang"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SS -- $SS
        n_t         n_j integral_SI  integral_I 
   842.0000    772.0000 345416.5338    775.2242 
   
Noe: f_log is one portion of the likelihood on which beta is constant. Calculate the complete data likelihood by adding the f_logs together.

```{r}
#' Log likelihood of the stochastic SIR model
#'
#'
#' allows non-Markovian dynamics through Weibull-distribution infectious periods (Streftaris and Gibson, 2004)
#' allows generalized SIR process (Severo, 1969)
#' Severo, N. C. (1969). Generalizations of some stochastic epidemic models. Mathematical Biosciences, 4(3-4), 395-402.
#' Streftaris, G., & Gibson, G. J. (2004). Bayesian inference for stochastic epidemics in closed populations. Statistical Modelling, 4(1), 63-75.
#'
#'
#' @inheritParams rprop_x
#'
#' @param SS sufficient statistics of the current configuration of the latent data
#'
#' @return log likelihood
#' @export
#'
f_log_cp <- function(theta, SS, gener, b, iota_dist = "exponential") {

  # Setup
  gamma  <- theta[["gamma" ]]
  shape  <- theta[["shape" ]]
  lambda <- theta[["lambda"]]
  R0 <- theta[["R0"]]
  # theta[["beta"]] <- R0 * gamma / S0
  # beta   <- theta[["beta"  ]]

  n_T             <- SS[["n_T"            ]] # number observed infections by t_end
  I_tau_T         <- SS[["I_tau_T"        ]] 
  S_tau_T         <- SS[["S_tau_T"        ]]
  integral_SI     <- SS[["integral_SI"    ]]
  iota_removed    <- SS[["iota_removed"   ]]
  iota_infectious <- SS[["iota_infectious"]]


  # contribution of infections
  loglik_infec <- if(gener){
    n_T * log(beta) + sum(log(I_tau_T) - b * log(S_tau_T)) - beta  * integral_SI
  } else {
    n_T * log(beta) + sum(log(I_tau_T)) - beta  * integral_SI
  }

  # contribution of removals
  loglik_remov <-
    if(iota_dist == "exponential") {
      sum(stats::dexp(iota_removed   , gamma        , log   = TRUE                    )) + # removals before t_end (observed)
      sum(stats::pexp(iota_infectious, gamma        , log.p = TRUE, lower.tail = FALSE))   # removals after  t_end (not observed)
    } else if(iota_dist == "weibull") {
      sum(dweibull2  (iota_removed   , shape, lambda, log   = TRUE                    )) +
      sum(pweibull2  (iota_infectious, shape, lambda, log.p = TRUE, lower.tail = FALSE))
    }

  loglik <- loglik_infec 
  + loglik_remov

  return(loglik)

}
```