---
title: "Observed Data Plot"
author: "Jenny Yijian Huang"
date: "1/31/2022"
output: html_document
---

```{r}
#' Discrete incidence counts for infections
#'
#' Compute the number of infections in each observation interval
#'
#' @param x vector of infection times
#' @param ts observation schedule
#'
#' @return a vector of the number of infections in each time interval
#' @export
#'
#'
compute_Tk <- function(x, ts) {

  tau_T <- x[["tau_T"]]
  tau_T <- tau_T[is.finite(tau_T) & tau_T > 0] # exclude infinite values and zeros

  K     <- length(ts) - 1
  T_k   <- rep(NA, K)

  for(k in 1 : K) {
    T_k[k] <- sum(dplyr::between(tau_T, ts[k], ts[k + 1]))
  }

  return(T_k)

}
```

```{r}
#' Discrete the difference in I(k-1) - I(k) between observations.
#'
#' Compute the number of (infections MINUS recoveries) in each inter-observation interval for plotting.
#'
#' @param x vector of infection times
#' @param ts observation schedule
#'
#' @return a vector of the delta I(t) betw each time interval
#' @export
#'
#'
compute_delta_I <- function(x, ts) {
  
  K     <- length(ts) - 1
  delta_I   <- rep(NA, K)

  tau_T <- x[["tau_T"]]
  tau_T <- tau_T[is.finite(tau_T) & tau_T > 0] # exclude infinite values and zeros
  
  tau_J <- x[["tau_J"]]
  tau_J <- tau_J[is.finite(tau_J) & tau_J > 0] # exclude infinite values and zeros


  for(k in 1 : K) {
    delta_I[k] <- sum(dplyr::between(tau_T, ts[k], ts[k + 1])) - sum(dplyr::between(tau_J, ts[k], ts[k + 1])) # delta_I(t) = (new_infections - new_removals)
  }

  return(delta_I)

}
```

```{r}
#' Discrete the difference in I(k-1) - I(k) between observations.
#'
#' Compute the number of (infections MINUS recoveries) in each inter-observation interval for plotting.
#'
#' @param SEM all infection and recovery times
#' @param ts observation schedule
#' @param K number of observations
#'
#' @return the observed infection counts
#' @export
#'
#'
observed_data_plt <- function(SEM, K = 10, ts = NULL, type = "SIR") {

  # Setup
  t_end <- SEM[["t_end"]]
  x     <- SEM[["x"]]
  I0    <- SEM[["I0"]]
  S0    <- SEM[["S0"]]

  if(is.null(ts)){
    dt <- t_end / K
    ts <- seq(0, t_end, by = dt) # observation schedule (need not be regular)
  }

  # Observed difference in I(t) between T_(k-1) and T_k.
  delta_I <- compute_delta_I(x, ts = ts)
  if(type == "SEIR") F_k <- compute_Fk(x, ts = ts)

  # Output
  out <- list(delta_I = delta_I, I0 = I0, S0 = S0, ts = ts, t_end = t_end)
  if(type == "SEIR") out[["F_k"]] <- F_k
  return(out)

}
```


# Note: use observed_data_plt only for plotting the observations. Use observed_data to obtain the incidence data as a parameter to the mcmc.


#Example:

```{r}
test_trajectory <- MLE_test(
  S0 = 1e3, I0 = 1e1, t_end = 6,
  theta = list(R0 = c(2.5, 1.5, 3.5), gamma = 1, lambda = 1, shape = 1),
  change_day = c(2,4),
  iota_dist = "exponential",
  gener = FALSE, b = 1/2,
  E0 = 0, type = "SIR" # "SEIR"
)

test_trajectory_x <- test_trajectory$x

test_trajectory$MLE
```

```{r}
plot(x = test_trajectory$t[1:1500], y = test_trajectory$I[1:1500], main="Epidemic Trajectory",
   xlab="Time", ylab="I(t)")
```

```{r}
test_Y <- observed_data_plt(test_trajectory, K=10)

I_tau_plt <- test_Y$I0 + cumsum(test_Y$delta_I) # calculation for I(t) Compartment Counts.
plot(x = test_Y$ts, y = c(0, I_tau_plt), main="Observed Infections", xlab="Time", ylab="I(t)")
```

