---
title: "rprop_beta"
author: "Jenny Yijian Huang"
date: "11/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("Rlab")
library(Rlab)
```

# draw from (dbeta_star | dbeta)
```{r}
draw_dbeta <- function(prob, dbeta_j) {
  u <- sample(1:length(dbeta_j), 1)
  # changed_dbeta <- rbern(1, prob[u])
  # dbeta[u] <- changed_dbeta
  if(dbeta_j[u] == 1){
    dbeta[u] <- 0
  }
  else{
    dbeta[u] <- 1
  }
  return(dbeta)
}
```

```{r}
prob <- c(0.9, 0.9, 0.9, 0.8, 0.9, 0.9)
dbeta_j <- c(0,0,0,1,0,0)

dbeta_star <- draw_dbeta(prob, dbeta_j)
dbeta_star
```


# draw from (beta | dbeta_star, Z)
```{r}
# determine the change points according to dbeta_star.
segment_start <- c(1) # 1 will be the first start location.
segment_start <- append(segment_start, which(dbeta_star == 1)) # append the locations where dbeta == 1. These will be additional start locations.

segment_end <- c(length(dbeta))
segment_end <- append(which(dbeta_star == 1), segment_end) # the end of the segment corresponds to the start of the new segment.

# calculate segment_SS using the start and end points calculated.
segmented_SS <- suff_stat2(segment_start, segment_end, x, Y, gener, b, return_SI = FALSE) # here, x is x in the previous iteration: x^(j-1).
segmented_SS

beta_star <- c()
for (i in 1:length(segment_SS)) {
  print(i)
  beta_i <- gibbs_theta(segmented_SS[[i]], iota_dist, par_prior, A_theta, param, A_y)
  beta_star <- append(beta_star, beta_i)
}
```
