---
title: "Untitled"
author: "Jenny Yijian Huang"
date: "5/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# First, we simulate an epidemic with change points in R0 at weeks 2,4 using Gillespie's algorithm.
```{r}
cp_6 <- sim_changepoint_sem(
  S0 = 1e4, I0 = 1e1, t_end = 20,
  theta = list(R0 = c(2.00, 1.25, 1.50, 1.75, 2.00, 1.25), gamma = 1, lambda = 1, shape = 1),
  change_day = c(3,5,9,11,14),
  iota_dist = "exponential",
  gener = FALSE, b = 1/2,
  E0 = 0, type = "SIR" # "SEIR"
)
cp6_data <- cp_6$x
cp_6$MLE
```
```{r}
plot(x = cp_6$t[1:13500], y = cp_6$I[1:13500], main="Epidemic Trajectory",
   xlab="Time", ylab="I(t)")
abline(v=c(3,5,9,11,14),lwd=2,col="red")
```


```{r}
cp_Y_irreg <- observed_data(cp_6, K=20) 
cp_Y_irreg
```

```{r}
plot(x = cp_Y_irreg$ts, y = c(0, cp_Y_irreg$T_k), main="Observed Counts", xlab="Time", ylab="New Infections")
```

```{r}
sim_MM_irreg <- run_DAMCMC_complete_smallh6(
  theta0, cp_Y_irreg, N = 20000,
  rho = 0.2, param = "bg", approx = "ldp",
  iota_dist = "exponential", gener = FALSE, b = 1/2,
  thin = 1, plt = 2500,
  par_prior = list(
    a_beta = 1, b_beta = 1,
    a_gamma = 1, b_gamma = 1,
    a_R0 = 2, b_R0 = 2,
    a_lambda = 1, b_lambda = 1,
    a_pi11 = 1, b_pi11 = 10,
    a_pi01 = 500, b_pi01 = 500
  ), 
  length_delta = 19,
  x_b_ratio = 2,
  gamma=1
  )
```


```{r}
print(analyze_dbeta(sim_MM_irreg$dbeta_lst))
barplot(analyze_dbeta(sim_MM_irreg$dbeta_lst)[[2]], main="Delta Configurations", xlab="Change Point Location",  
 ylab="Count",names.arg = seq(1,19),
 border="blue")
# abline(h=1/2, col="blue", lty="dashed", lwd=4)
```
```{r}

```

