---
title: "Constant Beta experiment"
author: "Jenny Yijian Huang"
date: "2/20/2022"
output: html_document
---

# Constant Beta experiment

```{r}
#' Experiment 1: Proof of concept
#'
#' @param S0 size of initial susceptible population
#' @param I0 size initial infectious population
#' @param theta parameters of the SIR process
#' @param t_end end of observation period
#' @param K number of observation intervals
#' @param N number of iterations of the Markov chain
#' @param thin thinning parameter for the Markov chain
#' @param rho proportion of the latent data updated each iteration
#' @param param c("bg", "bR"); parameterize the models in terms of (beta, gamma) or (beta, R0)
#' @param approx c("poisson", "ldp"); whether to approximate the distribution of the infection times with a poisson process or a linear death process
#' @param iota_dist c("exponential", "weibull"); distribution of the infection period
#' @param gener logical; whether to use the generalized SIR of Severo (1972)
#' @param b parameter of the generalized SIR
#' @param path directory in which to save the figure
#' @param theta_0_factor factors by which the true value of the parameters is multiplied to initialize the Markov chain
#' @param plot_id name file for the figure(s)
#' @param save_fig logical; whether to save the figures generated
#'
#' @return list containing the parameters, observed data, Markov chain and run time of the algorithm
#' @export
#'
experiment_1_proof_of_concept <- function(
  S0 = 1e3, I0 = 1e1, theta = list(R0 = 2.5, lambda = 1, shape = 1, gamma = 1),
  t_end = 6, K = 10,
  N = 1e3, thin = 1, rho = 0.2, # 1/3
  param = "bR", approx = "ldp",
  iota_dist = "exponential",
  gener = FALSE, b = 1/2,
  theta_0_factor = 1,
  path = NULL, plot_id, save_fig = TRUE
  ) {

  theta <- complete_theta(theta, iota_dist, S0)

  # Observed data
  SIR   <- simulate_SEM(S0, I0, t_end, theta, iota_dist, gener, b)
  # if(save_fig)  draw_trajectories(SIR, plot_id, path, t_end)
  SIR$MLE
  Y     <- observed_data(SIR, K)
  Y <- cp_Y
  
  plot(x = Y$ts, y = c(0, Y$T_k), main= "Incidence Data (constant beta)", xlab="Time", ylab="New Infections")

  # run a long chain
  theta_0 <- purrr::map2(theta, theta_0_factor, `*`)
  if(iota_dist == "weibull")  theta_0[["shape"]] <- theta[["shape"]]

  MC <- run_DAMCMC(
    Y, N,
    rho, param, approx,
    iota_dist, gener, b,
    thin, theta_0
    )

  return(list(theta = theta, Y = Y, MC = MC, SIR = SIR, thin = thin))

}
```

```{r}
experiment1 <- experiment_1_proof_of_concept(
  S0 = 1e3, I0 = 1e1, theta = list(R0 = 2.5, lambda = 1, shape = 1, gamma = 1),
  t_end = 6, K = 10,
  N = 20000, thin = 1, rho = 0.2,
  param = "bg", approx = "ldp",
  iota_dist = "exponential",
  gener = FALSE, b = 1/2,
  theta_0_factor = 1,
  path = NULL, plot_id = "experiment1", save_fig = FALSE
  )
```


```{r}
experiment1$SIR$MLE
# theta0_constant <- list("R0" = 1, "beta" = 0.0025, "lambda" = 1, "shape" = 1, "gamma" = 1)
```

```{r}
# create dataframe
theta         <- experiment1$MC[["theta"      ]] # a list where each element is 1 iteration of values.
loglik        <- experiment1$MC[["loglik"     ]]
thin          <- 1
# if(do_SS)  SS <- experiment1[["SS"         ]]
rate_accept_constant_beta   <- experiment1$MC[["rate_accept"]]
S0            <- experiment1$MC[["S0"         ]]
run_time      <- experiment1$MC[["run_time"   ]]
  
# Data Wrangling
theta_tidy <- data.table::rbindlist(theta) %>%
  add_iteration(thin) %>%
  dplyr::mutate(loglik = loglik) %>%
  dplyr::filter(.data$Iteration <= 20000) %>%
  remove_burnin(1000) %>%
  dplyr::mutate(expected_infection_length = 1 / gamma)

```

```{r}
# Posterior Means
theta_tidy %>%
    dplyr::select(- .data$Iteration, - .data$loglik) %>%
    {tibble::tibble(
      var  = colnames(.),
      mean = colMeans(.)
    )}

ESS         = coda::effectiveSize(coda::mcmc(theta_tidy))
rate_accept_constant_beta
ESS
# posterior quantile
quantile(theta_tidy$beta, probs = c(0.025, 0.5, 0.975))
``` 

```{r}
# Plot constant beta results
print(draw_tp(theta_tidy, "beta"))
print(draw_histogram2(theta_tidy, "beta", bins = 10, 0.002236052, 0.004057099))
print(draw_acf(theta_tidy, "beta", 200))
```
Estimate of beta is slightly biased downwards compared to in the change point case. Also, the ESS is 53 compared to the change point algorithm ~100. Could this be because we are keeping gamma constant in the change point case.

 2.5%         50%       97.5% 
0.002236052 0.003382330 0.004057099 

Mean: 0.003276901
ESS: 4.366173
Acceptance Rate: 0.04535


